/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formulario;
import java.sql.Connection;//para manejo de las conexiones
import java.sql.Statement;//para manejo de sentencias
import java.sql.PreparedStatement;//sentencias preparadas
import java.util.logging.Level;
import Conexion.CreateConnection;//Clase Generica
import java.sql.SQLException;//manejo de errores
import javax.swing.JOptionPane;//
import java.sql.ResultSet;
import java.sql.DriverManager;
/**
 *
 * @author ricar
 */
public class Empleado2 extends javax.swing.JFrame {
    CreateConnection conexionPostgres = new CreateConnection();
    Connection con;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Empleado2.class.getName());

    /**
     * Creates new form Empleado2
     */
    public Empleado2() throws SQLException {
        initComponents();
        con = conexionPostgres.getConnection();
    }
//hola mundo
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConsultar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtSalario = new javax.swing.JTextField();
        LbId = new javax.swing.JLabel();
        LbNombre = new javax.swing.JLabel();
        LbApellido = new javax.swing.JLabel();
        LbSalario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        LbId.setText("Id");

        LbNombre.setText("Nombre");

        LbApellido.setText("Apellido");

        LbSalario.setText("Salario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbId, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnConsultar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LbNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LbApellido, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LbSalario, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btnActualizar)
                        .addGap(60, 60, 60)
                        .addComponent(btnGuardar)
                        .addGap(33, 33, 33)
                        .addComponent(btnEliminar)
                        .addGap(104, 104, 104))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtId, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtApellido)
                            .addComponent(txtSalario, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbId))
                        .addGap(37, 37, 37)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LbNombre))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbApellido))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbSalario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnGuardar)
                    .addComponent(btnActualizar)
                    .addComponent(btnConsultar))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void getEmpleado(int Id){


        try{
           String qry = "select id,nombre,apellido,salario form public.empleado where ID = ?";
           //String mensaje = JOptionPane.showInputDialog("Ingrese el codigo a elminiar");
                    
     
           PreparedStatement ps = con.prepareStatement(qry);
           ps.setInt(1,Id);
           ResultSet rs=ps.executeQuery(qry);
           while (rs.next()){
               txtNombre.setText(rs.getString("nombre"));
               txtApellido.setText(rs.getString("apellido"));
               txtSalario.setText(rs.getString("salario"));
               txtId.setText(rs.getString("id"));
           }
           JOptionPane.showMessageDialog(null,"Total de Registros elimindaos");
           ps.close();
            
        } catch (SQLException e){
            e.getMessage();
        }
    }
    public void guardarEmpleadoPS(){
        try{
           //Extraer valores que tiene en la interfaz de los JText
            String nombre = txtNombre.getText();
            String apellido = txtApellido.getText();
            String salario = txtSalario.getText();

                       //es mi sentencia
           String qry = "insert into public.empleado(nombre,apellido,salario)"
                    + "values(?,?,?)";
            
            //ejecuta la sentencia a la base de datos, la cual retorna un int

            //espacio de trabajo que lleva la conexion para escribir sentencias SQL
           PreparedStatement ps = con.prepareStatement(qry);
           ps.setString(1, nombre);
           ps.setString(2,apellido);
           ps.setDouble(3,Double.parseDouble(salario));
           int filasInsertadas = ps.executeUpdate(qry);
           
           JOptionPane.showMessageDialog(null,"Total de Registros insertados"+filasInsertadas);
           ps.close();
            
        } catch (SQLException e){
            e.getMessage();
        }
    }
    public void eliminarEmpleado(){
        try{
           String qry = "delete from public.empleado where Id=?";
           String mensaje = JOptionPane.showInputDialog("Ingrese el codigo a elminiar");
                    
     
           PreparedStatement ps = con.prepareStatement(qry);
           ps.setInt(1, Integer.parseInt(mensaje));
           int filasEliminadas = ps.executeUpdate(qry);
           
           JOptionPane.showMessageDialog(null,"Total de Registros elimindaos"+filasEliminadas);
           ps.close();
            
        } catch (SQLException e){
            e.getMessage();
        }
    }
    
    
    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        getEmpleado(Integer.parseInt(txtId.getText()));
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        guardarEmpleadoPS();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminarEmpleado();
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Empleado2().setVisible(true);
            } catch (SQLException ex) {
                System.getLogger(Empleado2.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        }
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbApellido;
    private javax.swing.JLabel LbId;
    private javax.swing.JLabel LbNombre;
    private javax.swing.JLabel LbSalario;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSalario;
    // End of variables declaration//GEN-END:variables
}
